# Generated by Django 5.1.4 on 2026-06-09 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مفهوم کلیدی یا عنوان کوتاه سوال', max_length=255, verbose_name='Title/Concept')),
                ('body', models.TextField(help_text='صورت کامل سوال یا سناریوی مطرح شده', verbose_name='Question Body/Scenario')),
                ('estimated_time', models.PositiveIntegerField(default=120, help_text='زمان پیشنهادی برای پاسخ به این سوال', verbose_name='Estimated Time (Seconds)')),
                ('code_template', models.TextField(blank=True, help_text='قالب کد اولیه برای سوالات کدنویسی', null=True, verbose_name='Code Template')),
                ('question_type', models.CharField(choices=[('technical', 'Technical / Coding'), ('multiple_choice', 'Multiple Choice / Quiz'), ('architecture', 'Architecture / Design Patterns'), ('system_design', 'System Design'), ('devops', 'DevOps / Infrastructure'), ('behavioral', 'Behavioral / HR')], db_index=True, default='technical', max_length=30, verbose_name='Question Type')),
                ('seniority_level', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid_level', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead / Principal')], db_index=True, default='mid_level', max_length=20, verbose_name='Seniority Level')),
                ('reference_answer', models.TextField(help_text='پاسخ ایده\u200cآل و نکات کلیدی برای راهنمایی تصحیح هوش مصنوعی', verbose_name='Reference Answer')),
                ('ai_evaluation_criteria', models.JSONField(blank=True, default=dict, help_text='کلیدواژه\u200cهای اجباری و وزن نمره\u200cدهی', verbose_name='AI Evaluation Criteria')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('source', models.CharField(choices=[('manual', 'Manually Added'), ('ai_generated', 'AI Generated & Cached'), ('github_import', 'Imported from GitHub')], default='manual', max_length=20, verbose_name='Source')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Source URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='questions/attachments/', verbose_name='Attachment File')),
                ('attachment_type', models.CharField(choices=[('image', 'Diagram / Image'), ('code_file', 'Configuration / Source Code File'), ('document', 'Supplementary Document')], default='code_file', max_length=20, verbose_name='Attachment Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='questions.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question Attachment',
                'verbose_name_plural': 'Question Attachments',
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='questions.questioncategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Question Category',
                'verbose_name_plural': 'Question Categories',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(related_name='questions', to='questions.questioncategory', verbose_name='Categories / Skills'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct Option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'seniority_level', 'is_active'], name='questions_q_questio_1dc036_idx'),
        ),
    ]
