# Generated by Django 5.1.4 on 2026-06-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_banned",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="مسدود شده"
            ),
        ),
    ]
