# Generated by Django 5.1.4 on 2026-06-11 01:53

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="شناسه یکتا")),
                (
                    "target_position",
                    models.CharField(
                        help_text="مثال: Senior Django Developer", max_length=150, verbose_name="موقعیت شغلی هدف"
                    ),
                ),
                (
                    "seniority_level",
                    models.CharField(
                        choices=[
                            ("intern", "کارآموز"),
                            ("junior", "جونیور"),
                            ("mid_level", "میدلول"),
                            ("senior", "سنیور"),
                            ("lead", "لید"),
                        ],
                        default="mid_level",
                        max_length=20,
                        verbose_name="سطح ارشدیت",
                    ),
                ),
                (
                    "job_description",
                    models.TextField(
                        blank=True, help_text="اختیاری — برای شخصی\u200cسازی مصاحبه", verbose_name="متن آگهی استخدام"
                    ),
                ),
                (
                    "focus_topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='مثال: ["Django", "PostgreSQL", "Docker"]',
                        verbose_name="موضوعات تمرکز",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("setup", "در حال تنظیم"),
                            ("intro", "معارفه"),
                            ("questioning", "در حال سوال"),
                            ("drilling", "سوال تعقیبی"),
                            ("wrap_up", "جمع\u200cبندی"),
                            ("completed", "تکمیل شده"),
                            ("abandoned", "رها شده"),
                        ],
                        db_index=True,
                        default="setup",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "current_question_index",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ایندکس سوال فعلی"),
                ),
                ("total_questions", models.PositiveSmallIntegerField(default=10, verbose_name="تعداد کل سوالات")),
                (
                    "final_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نمره نهایی",
                    ),
                ),
                (
                    "final_report",
                    models.JSONField(
                        blank=True, help_text="گزارش کامل مصاحبه به فرمت JSON", null=True, verbose_name="گزارش نهایی"
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="خلاصه مصاحبه")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="زمان شروع")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="زمان پایان")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه مصاحبه",
                "verbose_name_plural": "جلسات مصاحبه",
                "db_table": "interview_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(verbose_name="ترتیب")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("active", "فعال"),
                            ("answered", "پاسخ داده شده"),
                            ("skipped", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_entries",
                        to="questions.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_questions",
                        to="interviews.interviewsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال جلسه",
                "verbose_name_plural": "سوالات جلسه",
                "db_table": "session_questions",
                "ordering": ["order"],
                "unique_together": {("session", "order"), ("session", "question")},
            },
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="selected_questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="sessions",
                through="interviews.SessionQuestion",
                to="questions.question",
                verbose_name="سوالات انتخابی",
            ),
        ),
        migrations.CreateModel(
            name="InterviewMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("system", "سیستم"), ("assistant", "مصاحبه\u200cکننده"), ("user", "کاربر")],
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("greeting", "خوش\u200cآمدگویی"),
                            ("question", "سوال اصلی"),
                            ("follow_up", "سوال تعقیبی"),
                            ("user_answer", "پاسخ کاربر"),
                            ("feedback", "بازخورد"),
                            ("transition", "انتقال بین سوالات"),
                            ("wrap_up", "جمع\u200cبندی"),
                            ("system_event", "رویداد سیستمی"),
                        ],
                        default="user_answer",
                        max_length=20,
                        verbose_name="نوع پیام",
                    ),
                ),
                ("content", models.TextField(verbose_name="محتوا")),
                ("turn_number", models.PositiveSmallIntegerField(verbose_name="شماره نوبت")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="tool calls، token usage و اطلاعات اضافی",
                        verbose_name="متادیتا",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="زمان ایجاد")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="interviews.interviewsession",
                        verbose_name="جلسه",
                    ),
                ),
                (
                    "related_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="interviews.sessionquestion",
                        verbose_name="سوال مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام مصاحبه",
                "verbose_name_plural": "پیام\u200cهای مصاحبه",
                "db_table": "interview_messages",
                "ordering": ["turn_number"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer_text", models.TextField(verbose_name="متن پاسخ")),
                (
                    "answer_duration",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="مدت زمان پاسخ (ثانیه)"),
                ),
                ("follow_up_asked", models.BooleanField(default=False, verbose_name="سوال تعقیبی پرسیده شد")),
                ("follow_up_answer", models.TextField(blank=True, verbose_name="پاسخ سوال تعقیبی")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "در انتظار تصحیح"), ("graded", "تصحیح شده"), ("failed", "خطا در تصحیح")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت ارزیابی",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نمره (0-100)",
                    ),
                ),
                ("technical_accuracy", models.TextField(blank=True, verbose_name="دقت فنی")),
                ("strengths", models.JSONField(blank=True, default=list, verbose_name="نقاط قوت")),
                ("weaknesses", models.JSONField(blank=True, default=list, verbose_name="نقاط ضعف")),
                (
                    "missing_keywords",
                    models.JSONField(blank=True, default=list, verbose_name="کلیدواژه\u200cهای جامانده"),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="بازخورد تشریحی")),
                ("suggested_follow_up", models.TextField(blank=True, verbose_name="سوال تعقیبی پیشنهادی")),
                ("raw_evaluation", models.JSONField(blank=True, null=True, verbose_name="خروجی خام هوش مصنوعی")),
                ("error_log", models.TextField(blank=True, verbose_name="لاگ خطا")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد")),
                ("evaluated_at", models.DateTimeField(blank=True, null=True, verbose_name="زمان ارزیابی")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_answers",
                        to="questions.question",
                        verbose_name="سوال",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="interviews.interviewsession",
                        verbose_name="جلسه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ کاربر",
                "verbose_name_plural": "پاسخ\u200cهای کاربران",
                "db_table": "user_answers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="interviewsession",
            index=models.Index(fields=["user", "status"], name="interview_s_user_id_88a9f3_idx"),
        ),
        migrations.AddIndex(
            model_name="interviewsession",
            index=models.Index(fields=["user", "created_at"], name="interview_s_user_id_c20944_idx"),
        ),
        migrations.AddIndex(
            model_name="interviewmessage",
            index=models.Index(fields=["session", "turn_number"], name="interview_m_session_2a3974_idx"),
        ),
        migrations.AddIndex(
            model_name="interviewmessage",
            index=models.Index(fields=["session", "role"], name="interview_m_session_120266_idx"),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(fields=["session", "status"], name="user_answer_session_89669e_idx"),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(fields=["user", "status"], name="user_answer_user_id_2b0112_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("session", "question")},
        ),
    ]
