# Generated by Django 5.1.4 on 2026-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="زمان بروزرسانی"),
        ),
    ]
