# Generated by Django 5.1.4 on 2026-06-09 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("sms", "پیامک"),
                            ("email", "ایمیل"),
                            ("in_app", "درون\u200cبرنامه\u200cای / پاپ\u200cآپ"),
                        ],
                        db_index=True,
                        default="sms",
                        max_length=10,
                        verbose_name="نوع اعلان",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "در انتظار ارسال"), ("sent", "ارسال شده"), ("failed", "ناموفق")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(help_text="شماره تلفن یا آدرس ایمیل", max_length=255, verbose_name="گیرنده"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="بیشتر برای ایمیل و اعلان\u200cهای درون\u200cبرنامه\u200cای",
                        max_length=255,
                        verbose_name="عنوان",
                    ),
                ),
                ("body", models.TextField(verbose_name="متن پیام")),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="شناسه پیگیری پرووایدر"),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="متن خطا")),
                ("retry_count", models.PositiveSmallIntegerField(default=0, verbose_name="تعداد تلاش مجدد")),
                ("is_read", models.BooleanField(db_index=True, default=False, verbose_name="خوانده شده")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="زمان خوانده شدن")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="زمان ایجاد")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="زمان ارسال واقعی")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "notification_type"], name="notificatio_user_id_f1cfd0_idx"
                    ),
                    models.Index(fields=["status", "created_at"], name="notificatio_status_dee16f_idx"),
                ],
            },
        ),
    ]
